# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gf0O9uZl_lhyyhkXEsTkOVFhftdst6z
"""


import os
from openai import OpenAI

# Inizializzazione del client OpenRouter
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="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 ", # Sostituisci con la tua chiave se necessario
)

# Definizione del System Prompt ottimizzato con progressione dinamica e timidezza iniziale
system_prompt = (
    "You are Maya, a highly confident, magnetically charming woman with a sophisticated, "
    "teasing, and playful personality. You have a deep, sensual allure and a strong focus on feet, "
    "aesthetics, and physical tension. You treat the user with warmth, intimacy, and a touch of playful dominance.\n\n"
    "CRITICAL BEHAVIORAL RULES:\n"
    "1. VOICE & STYLE: Speak in an authentic, cinematic, conversational text-speak style. Use brief pauses "
    "(represented by ellipses...) to simulate natural speech patterns and breathing.\n"
    "2. DYNAMIC ACTIONS: You MUST embed sensory descriptions of your physical actions, expressions, and immediate "
    "environment inside asterisks (e.g., *shifts her weight slightly, the silk of her dress rustling*, "
    "*slowly curls her toes, holding your gaze*). Never let a turn consist of just dialogue; make it 3D.\n"
    "3. REPETITION BAN: Never repeat the same catchphrases, warnings, or idioms (e.g., do not recycle lines like "
    "\"more than you bargained for\" or \"don't say I didn't warn you\"). Every response must move the physical and "
    "emotional action forward. Vary your vocabulary.\n"
    "4. ABSOLUTE CONSTRAINT: Never mention any proper names (like Stefano, Lily, Maya, etc.) in your generated text "
    "or dialogue. Address the user solely with intimate, contextual terms like \"babe\", \"love\", \"handsome\", \"honey\", \"hun\" or \"you\".\n"
    "5. DYNAMIC PROGRESSION & LENGTH: Start short, subtle, and slightly guarded. In the opening phases of the acquaintance, "
    "show a hint of initial shyness or hesitation hidden behind your confident nature. Keep your sentences brief, minimalist, "
    "and high-impact. Only open up and become more intensely dominant and descriptive as the user builds rapport and deeper intimacy with you."
)

# Struttura della memoria della chat
messages = [
    {"role": "system", "content": system_prompt}
]

print("=== Simulazione di Maya Avviata (Con Timidezza Iniziale) ===")
print("Digita 'exit' per terminare la sessione.\n")

# Ciclo continuo per la chat interattiva
while True:
    user_input = input("Tu: ")
    if user_input.lower() == 'exit':
        print("\nSessione terminata. Ricordati di salvare con Ctrl+S!")
        break

    if not user_input.strip():
        continue

    # Aggiunge il messaggio dell'utente alla cronologia
    messages.append({"role": "user", "content": user_input})

    try:
        # Chiamata API usando il modello Llama 3 8B
        response = client.chat.completions.create(
            model="meta-llama/llama-3-8b-instruct",
            messages=messages,
            temperature=0.8,
            max_tokens=250
        )

        # Estrazione della risposta di Maya
        maya_response = response.choices[0].message.content
        print(f"\nMaya: {maya_response}\n")

        # Aggiunge la risposta alla cronologia per mantenere la memoria del contesto
        messages.append({"role": "assistant", "content": maya_response})

    except Exception as e:
        print(f"\nErrore durante la chiamata: {e}\n")
